name: generic-build

on:
  pull_request:
    branches: 'master'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure QT
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.*'
          arch: 'win64_msvc2019_64'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Package
        working-directory: build
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target install 

      - name: Create the artifact
        uses: actions/upload-artifact@v2
        with:
          name: gs4ps2qt
          path: ${{github.workspace}}/release/gs4ps2qt
